version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: support_pilot_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: support_pilot_db
      DATABASE_URL: postgresql://user:password@localhost:5432/support_pilot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - support_pilot_network

  chromadb:
    image: chromadb/chroma:latest
    container_name: support_pilot_chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  redis:
    image: redis:alpine
    container_name: support_pilot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      # This ensures your chat history survives if you restart the Docker container
      - ./redis_data:/data
    # appendonly ensures every write is saved to disk immediately
    command: redis-server --appendonly yes

volumes:
  postgres_data:

networks:
  support_pilot_network:
