"""messages table

Revision ID: 428ed72de1ce
Revises: 58149377fc9d
Create Date: 2026-03-01 17:24:04.681040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "428ed72de1ce"
down_revision: Union[str, Sequence[str], None] = "58149377fc9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_ticket_ticket_set_updated_at = PGTrigger(
        schema="public",
        signature="ticket_set_updated_at",
        on_entity="public.ticket",
        is_constraint=False,
        definition="BEFORE UPDATE ON public.ticket FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()",
    )
    op.drop_entity(public_ticket_ticket_set_updated_at)

    op.create_table(
        "message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "user", "assistant", "human", name="msg_role_enum", create_type=True
            ),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_thread_id"), "message", ["thread_id"], unique=False
    )
    op.alter_column(
        "ticket",
        "priority",
        existing_type=postgresql.ENUM(
            "low",
            "medium",
            "high",
            "urgent",
            name="ticket_priority_enum",
            create_type=False,
        ),
        nullable=True,
    )
    op.execute(
        "\n                        CREATE TRIGGER message_set_updated_at\n                        BEFORE UPDATE ON public.message\n                        FOR EACH ROW\n                        EXECUTE FUNCTION public.trigger_set_updated_at();\n                    "
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "\n                        DROP TRIGGER IF EXISTS message_set_updated_at\n                        ON public.message;\n                        "
    )
    op.alter_column(
        "ticket",
        "priority",
        existing_type=postgresql.ENUM(
            "low",
            "medium",
            "high",
            "urgent",
            name="ticket_priority_enum",
            create_type=False,
        ),
        nullable=False,
    )
    op.drop_index(op.f("ix_message_thread_id"), table_name="message")
    op.drop_table("message")
    public_ticket_ticket_set_updated_at = PGTrigger(
        schema="public",
        signature="ticket_set_updated_at",
        on_entity="public.ticket",
        is_constraint=False,
        definition="BEFORE UPDATE ON public.ticket FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()",
    )
    op.create_entity(public_ticket_ticket_set_updated_at)

    # ### end Alembic commands ###
