"""tickets table

Revision ID: 58149377fc9d
Revises: cd0ad60b31d2
Create Date: 2026-02-28 22:25:41.529683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58149377fc9d"
down_revision: Union[str, Sequence[str], None] = "cd0ad60b31d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_order_order_set_updated_at = PGTrigger(
        schema="public",
        signature="order_set_updated_at",
        on_entity="public.order",
        is_constraint=False,
        definition='BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()',
    )
    op.drop_entity(public_order_order_set_updated_at)

    op.create_table(
        "ticket",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "billing",
                "technical",
                "login",
                "general",
                name="ticket_category_enum",
                create_type=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "low",
                "medium",
                "high",
                "urgent",
                name="ticket_priority_enum",
                create_type=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ai_handling",
                "escaled_to_human",
                "human_handling",
                "closed",
                name="ticket_status_enum",
                create_type=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_order_id"), "ticket", ["order_id"], unique=False)
    op.execute(
        "\n                        CREATE TRIGGER ticket_set_updated_at\n                        BEFORE UPDATE ON public.ticket\n                        FOR EACH ROW\n                        EXECUTE FUNCTION public.trigger_set_updated_at();\n                    "
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "\n                        DROP TRIGGER IF EXISTS ticket_set_updated_at\n                        ON public.ticket;\n                        "
    )
    op.drop_index(op.f("ix_ticket_order_id"), table_name="ticket")
    op.drop_table("ticket")
    public_order_order_set_updated_at = PGTrigger(
        schema="public",
        signature="order_set_updated_at",
        on_entity="public.order",
        is_constraint=False,
        definition='BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at()',
    )
    op.create_entity(public_order_order_set_updated_at)

    # ### end Alembic commands ###
