"""conversation and message table

Revision ID: 75e9e2450e31
Revises: 
Create Date: 2026-02-22 14:22:41.320752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75e9e2450e31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_trigger_set_updated_at = PGFunction(
        schema="public",
        signature="trigger_set_updated_at()",
        definition='RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.updated_at = NOW();\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql'
    )
    op.create_entity(public_trigger_set_updated_at)

    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'assistant', name='message_role_enum', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.execute('\n                        CREATE TRIGGER conversation_set_updated_at\n                        BEFORE UPDATE ON public.conversation\n                        FOR EACH ROW\n                        EXECUTE FUNCTION public.trigger_set_updated_at();\n                    ')
    op.execute('\n                        CREATE TRIGGER message_set_updated_at\n                        BEFORE UPDATE ON public.message\n                        FOR EACH ROW\n                        EXECUTE FUNCTION public.trigger_set_updated_at();\n                    ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('\n                        DROP TRIGGER IF EXISTS message_set_updated_at\n                        ON public.message;\n                        ')
    op.execute('\n                        DROP TRIGGER IF EXISTS conversation_set_updated_at\n                        ON public.conversation;\n                        ')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('conversation')
    public_trigger_set_updated_at = PGFunction(
        schema="public",
        signature="trigger_set_updated_at()",
        definition='RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.updated_at = NOW();\n            RETURN NEW;\n        END;\n        $$ LANGUAGE plpgsql'
    )
    op.drop_entity(public_trigger_set_updated_at)

    # ### end Alembic commands ###
