"""orders table

Revision ID: cd0ad60b31d2
Revises: 
Create Date: 2026-02-27 22:28:53.528054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd0ad60b31d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('delivery_notes', sa.String(length=255), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('order_status', postgresql.ENUM('pending', 'preparing', 'out_for_delivery', 'delivered', 'cancelled', name='order_status_enum', create_type=True), nullable=False),
    sa.Column('payment_status', postgresql.ENUM('unpaid', 'paid', 'refunded', name='payment_status_enum', create_type=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('\n                        CREATE TRIGGER order_set_updated_at\n                        BEFORE UPDATE ON public.order\n                        FOR EACH ROW\n                        EXECUTE FUNCTION public.trigger_set_updated_at();\n                    ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('\n                        DROP TRIGGER IF EXISTS order_set_updated_at\n                        ON public.order;\n                        ')
    op.drop_table('order')
    # ### end Alembic commands ###
